In [1]:
import pandas as pd

In [25]:
# Использую sheet_name=None чтобы загрузить все листы excel
data = pd.read_excel('/mnt/HC_Volume_18315164/home-jupyter/jupyter-ro-a/Vizualisation/BI-sys/Данные_вариант1.xlsx', sheet_name=None)

In [28]:
# Создаю переменную под лист из excel. Название листа в скобках
product = data['Products']
dynamic = data['Dynamic']

In [30]:
product

,SKU,Категория,Предмет,Бренд,Цена (Декабрь),Цена (Ноябрь),Продажи (Декабрь),Продажи (Ноябрь),Выручка (Декабрь),Выручка (Ноябрь),Средний % выкупа (Декабрь),Средний % выкупа (Ноябрь),Страна
0,13856867,Уход за кожей,Скрабы,The Act express recovery,413,388.51,109619,110053,45262341,42756691.03,0.96,0.93,Россия
1,46825817,Уход за кожей,Кремы,EpilProfi,839,839.09,48308,48946,40531273,41070099.14,0.96,0.94,Россия
2,51524888,Профессиональная косметика,Гели для бровей,PUSY,850,856.63,40756,39432,34642600,33778634.16,0.96,0.99,Россия
3,56236410,Средства личной гигиены,Влажные салфетки,FRESHLAND,543,555.59,50150,44773,27223489,24875431.07,0.99,1.00,Россия
4,16898570,Макияж,Туши,LUXVISAGE,314,299.82,64598,71601,20294736,21467411.82,0.97,0.94,Беларусь
...,...,...,...,...,...,...,...,...,...,...,...,...,...
91327,116743477,Ногти,Шаблоны для моделирования ногтей,iNVENT P,53,50.97,1,1,53,50.97,0.95,0.95,Россия
91328,104040577,Ногти,Декор для маникюра,iNVENT PRiNT,53,53.24,1,1,53,53.24,0.93,0.93,Россия
91329,43227412,Ногти,Шаблоны для моделирования ногтей,iNVENT P,53,49.55,1,1,53,49.55,0.95,0.95,Россия
91330,104042101,Ногти,Шаблоны для моделирования ногтей,iNVENT P,53,54.93,1,1,53,54.93,0.95,0.95,Россия
91331,42387699,Ногти,Шаблоны для моделирования ногтей,Anna Tkacheva,51,48.72,1,1,51,48.72,0.95,0.95,Россия

In [33]:
dynamic

             Бренд      Месяц  Продажи      Выручка  Средний % выкупа
0     188cosmetics 2023-12-01     5844   2315498.00             0.960
1     188cosmetics 2023-11-01     4423   1890118.20             0.964
2     188cosmetics 2023-10-01     3093   1225502.00             0.901
3     188cosmetics 2023-09-01     3399   1346745.00             0.920
4     188cosmetics 2023-08-01     3685   1460063.00             0.884
...            ...        ...      ...          ...               ...
5995       Я САМАЯ 2023-11-01    34937  10588391.76             0.983
5996       Я САМАЯ 2023-10-01    28159   8343811.00             0.915
5997       Я САМАЯ 2023-09-01    26194   7761561.00             0.877
5998       Я САМАЯ 2023-08-01    27830   8246325.00             0.934
5999       Я САМАЯ 2023-07-01    23759   7040045.00             0.866

[6000 rows x 5 columns]

In [34]:
df = pd.merge(product, dynamic, on='Бренд')

In [43]:
# У какого бренда больше всего уникальных SKU?
df.groupby('Бренд', as_index=False).agg({'SKU':'count'}).sort_values('SKU', ascending=False)

                                          Бренд   SKU
443                                   LUXVISAGE  9246
25                                         AVON  8256
856                                       irisk  6972
647                                     RELOUIS  6732
682                                       SHAIK  6456
..                                          ...   ...
430                                     LIANORA    12
170                                      Cullin    12
421                              LA BEAUTY CLUB    12
523  Maybelline New York Тушь черная для ресниц    12
972                           СОЛНЦЕ И ЛУНА ECO    12

[1000 rows x 2 columns]