In [3]:
import pandas as pd
from operator import attrgetter
import seaborn as sns
from matplotlib import pyplot as plt
from matplotlib import colors as mcolors
import numpy as np

In [4]:
data = pd.read_csv('/mnt/HC_Volume_18315164/home-jupyter/jupyter-ro-a/product/Данные.csv', index_col=0)

In [5]:
data.head()

  dlk_cob_date                               user_id
0   2023-08-22  a95b0e7e-deda-4cb8-81d2-cff4a01e9077
1   2023-06-12  4f53a875-847f-47cb-ab16-3517ca9cf92c
2   2024-08-15  f04fb972-ff9c-41ce-8dbc-a0984e6017ae
3   2023-12-08  1d9bcb51-351d-4679-8aba-95f38b9c56e9
4   2024-10-15  21d807eb-1ae4-4061-a403-96b5eefdd312

In [6]:
data['dlk_cob_date'] = pd.to_datetime(data['dlk_cob_date'])

In [7]:
data_copy = data

In [8]:
data_copy['order_period'] = data_copy['dlk_cob_date'].dt.to_period('M')

In [9]:
data_copy['order_period_day'] = data_copy['dlk_cob_date'].dt.to_period('D')

In [10]:
data_copy['cohort'] = data_copy.groupby('user_id')['dlk_cob_date'].transform('min').dt.to_period('M')

In [11]:
data_copy['cohort_day'] = data_copy.groupby('user_id')['dlk_cob_date'].transform('min').dt.to_period('D')

In [12]:
data_copy['period_number_month'] = np.floor((data_copy.order_period_day - data_copy.cohort_day).apply(attrgetter('n'))/30)

In [13]:
df_cohort = data_copy.groupby(['cohort', 'period_number_month']).agg(n_customers=('user_id', 'nunique')).reset_index()

In [14]:
df_cohort

      cohort  period_number_month  n_customers
0    2023-01                  0.0          162
1    2023-01                  1.0           81
2    2023-01                  2.0           90
3    2023-01                  3.0           77
4    2023-01                  4.0           69
..       ...                  ...          ...
248  2024-08                  1.0          117
249  2024-08                  2.0           41
250  2024-09                  0.0          258
251  2024-09                  1.0           56
252  2024-10                  0.0          180

[253 rows x 3 columns]

In [15]:
cohort_pivot = df_cohort.pivot_table(index='cohort', columns='period_number_month', values='n_customers')

In [16]:
cohort_size = cohort_pivot.iloc[:,0]

In [17]:
pd.set_option('display.max_columns', None)

cohort_pivot

period_number_month,0.0,1.0,2.0,3.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0,11.0,12.0,13.0,14.0,15.0,16.0,17.0,18.0,19.0,20.0,21.0
cohort,,,,,,,,,,,,,,,,,,,,,,
2023-01,162.0,81.0,90.0,77.0,69.0,70.0,67.0,71.0,68.0,64.0,67.0,55.0,53.0,46.0,51.0,50.0,47.0,51.0,44.0,39.0,39.0,25.0
2023-02,138.0,49.0,48.0,45.0,44.0,41.0,38.0,33.0,43.0,41.0,43.0,42.0,42.0,35.0,39.0,37.0,30.0,33.0,35.0,27.0,17.0,NaN
2023-03,301.0,114.0,104.0,97.0,86.0,83.0,74.0,78.0,81.0,79.0,78.0,77.0,73.0,80.0,78.0,73.0,79.0,75.0,71.0,24.0,NaN,NaN
2023-04,591.0,213.0,178.0,179.0,172.0,169.0,178.0,146.0,137.0,135.0,139.0,129.0,138.0,135.0,132.0,128.0,119.0,116.0,94.0,NaN,NaN,NaN
2023-05,480.0,178.0,162.0,143.0,123.0,130.0,111.0,104.0,89.0,96.0,100.0,96.0,91.0,92.0,94.0,91.0,72.0,53.0,NaN,NaN,NaN,NaN
2023-06,589.0,199.0,173.0,168.0,167.0,159.0,138.0,119.0,103.0,119.0,109.0,111.0,106.0,107.0,89.0,88.0,56.0,NaN,NaN,NaN,NaN,NaN
2023-07,543.0,184.0,162.0,161.0,157.0,137.0,108.0,112.0,106.0,111.0,108.0,105.0,100.0,97.0,93.0,45.0,NaN,NaN,NaN,NaN,NaN,NaN
2023-08,743.0,264.0,235.0,210.0,181.0,172.0,174.0,143.0,146.0,147.0,138.0,137.0,129.0,114.0,59.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2023-09,752.0,259.0,218.0,180.0,168.0,142.0,122.0,129.0,125.0,133.0,134.0,115.0,102.0,51.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2023-10,833.0,298.0,259.0,230.0,214.0,198.0,179.0,182.0,170.0,182.0,160.0,152.0,87.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2023-11,709.0,238.0,204.0,172.0,156.0,155.0,146.0,148.0,130.0,123.0,120.0,72.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2023-12,683.0,269.0,217.0,202.0,197.0,186.0,182.0,167.0,153.0,154.0,71.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024-01,370.0,161.0,150.0,146.0,134.0,135.0,118.0,107.0,101.0,40.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024-02,386.0,173.0,131.0,130.0,127.0,121.0,105.0,99.0,49.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024-03,360.0,180.0,158.0,146.0,135.0,113.0,93.0,58.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024-04,393.0,204.0,175.0,162.0,141.0,128.0,63.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024-05,341.0,170.0,162.0,134.0,124.0,46.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024-06,356.0,171.0,147.0,130.0,70.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024-07,369.0,171.0,147.0,62.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024-08,256.0,117.0,41.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024-09,258.0,56.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024-10,180.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
x.iloc[3:4]

NameError: name 'x' is not defined

In [19]:
retention_matrix = cohort_pivot.divide(cohort_size, axis=0)

In [21]:
pd.set_option('display.max_columns', None)
retention_matrix

period_number_month,0.0,1.0,2.0,3.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0,11.0,12.0,13.0,14.0,15.0,16.0,17.0,18.0,19.0,20.0,21.0
cohort,,,,,,,,,,,,,,,,,,,,,,
2023-01,1.0,0.500000,0.555556,0.475309,0.425926,0.432099,0.413580,0.438272,0.419753,0.395062,0.413580,0.339506,0.327160,0.283951,0.314815,0.308642,0.290123,0.314815,0.271605,0.240741,0.240741,0.154321
2023-02,1.0,0.355072,0.347826,0.326087,0.318841,0.297101,0.275362,0.239130,0.311594,0.297101,0.311594,0.304348,0.304348,0.253623,0.282609,0.268116,0.217391,0.239130,0.253623,0.195652,0.123188,NaN
2023-03,1.0,0.378738,0.345515,0.322259,0.285714,0.275748,0.245847,0.259136,0.269103,0.262458,0.259136,0.255814,0.242525,0.265781,0.259136,0.242525,0.262458,0.249169,0.235880,0.079734,NaN,NaN
2023-04,1.0,0.360406,0.301184,0.302876,0.291032,0.285956,0.301184,0.247039,0.231810,0.228426,0.235195,0.218274,0.233503,0.228426,0.223350,0.216582,0.201354,0.196277,0.159052,NaN,NaN,NaN
2023-05,1.0,0.370833,0.337500,0.297917,0.256250,0.270833,0.231250,0.216667,0.185417,0.200000,0.208333,0.200000,0.189583,0.191667,0.195833,0.189583,0.150000,0.110417,NaN,NaN,NaN,NaN
2023-06,1.0,0.337861,0.293718,0.285229,0.283531,0.269949,0.234295,0.202037,0.174873,0.202037,0.185059,0.188455,0.179966,0.181664,0.151104,0.149406,0.095076,NaN,NaN,NaN,NaN,NaN
2023-07,1.0,0.338858,0.298343,0.296501,0.289134,0.252302,0.198895,0.206262,0.195212,0.204420,0.198895,0.193370,0.184162,0.178637,0.171271,0.082873,NaN,NaN,NaN,NaN,NaN,NaN
2023-08,1.0,0.355316,0.316285,0.282638,0.243607,0.231494,0.234186,0.192463,0.196501,0.197847,0.185734,0.184388,0.173620,0.153432,0.079408,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2023-09,1.0,0.344415,0.289894,0.239362,0.223404,0.188830,0.162234,0.171543,0.166223,0.176862,0.178191,0.152926,0.135638,0.067819,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2023-10,1.0,0.357743,0.310924,0.276110,0.256903,0.237695,0.214886,0.218487,0.204082,0.218487,0.192077,0.182473,0.104442,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2023-11,1.0,0.335684,0.287729,0.242595,0.220028,0.218618,0.205924,0.208745,0.183357,0.173484,0.169252,0.101551,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2023-12,1.0,0.393851,0.317716,0.295754,0.288433,0.272328,0.266471,0.244510,0.224012,0.225476,0.103953,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024-01,1.0,0.435135,0.405405,0.394595,0.362162,0.364865,0.318919,0.289189,0.272973,0.108108,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024-02,1.0,0.448187,0.339378,0.336788,0.329016,0.313472,0.272021,0.256477,0.126943,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024-03,1.0,0.500000,0.438889,0.405556,0.375000,0.313889,0.258333,0.161111,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024-04,1.0,0.519084,0.445293,0.412214,0.358779,0.325700,0.160305,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024-05,1.0,0.498534,0.475073,0.392962,0.363636,0.134897,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024-06,1.0,0.480337,0.412921,0.365169,0.196629,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024-07,1.0,0.463415,0.398374,0.168022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024-08,1.0,0.457031,0.160156,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024-09,1.0,0.217054,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024-10,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [31]:
round(0.218274, 2)

0.22

In [ ]:
100 36 30 30 29 30 30	0.247039	0.231810	0.228426	0.235195	0.218274	0.233503	0.228426	0.223350	0.216582	0.201354	0.196277	0.159052